- name: Install Apache2 and MariaDB
  remote_user: root

  hosts: web
  tasks:
  - name: Install Apache2
    ansible.builtin.package:
      name: httpd
      state: present

  - name: Install PHP
    ansible.builtin.package:
      name: php
      state: present

  - name: Install php modules
    yum:
      name: "{{ packages }}"
    vars:
      packages:
       - php-bcmath
       - php-bz2
       - php-gd
       - php-mbstring
       - php-mysqlnd
       - php-zip
       - php-xml

  - name: Restart Apache2
    ansible.builtin.service:
      name: httpd
      state: restarted
  
  - name: Open port 80
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled

