- name: Install Apache2
  remote_user: root
  hosts: web

  tasks:
  - name: Install Apache2
    ansible.builtin.package:
      name: httpd
      state: present

  - name: Install PHP
    ansible.builtin.package:
      name: php
      state: present

  - name: Install php modules
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - php-bcmath
      - php-bz2
      - php-gd
      - php-mbstring
      - php-mysqlnd
      - php-zip
      - php-xml
      - php-json

  - name: Restart Apache2
    ansible.builtin.service:
      name: httpd
      state: restarted
  
  - name: Open port 80
    ansible.posix.firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled

  - name: Restart Firewalld
    ansible.builtin.service:
      name: firewalld
      state: restarted

- name: Install MariaDB with an user
  remote_user: root
  hosts: database

  tasks:
  - name: Install MariaDB
    ansible.builtin.package:
      name: mariadb-server
      state: present
  
  - name: Open port 3306
    ansible.posix.firewalld:
      port: 3306/tcp
      permanent: yes
      state: enabled

  - name: Restart Firewalld
    ansible.builtin.service:
      name: firewalld
      state: restarted

  - name: MariaDB allow connection from all sources
    ansible.builtin.lineinfile:
      path: /etc/my.cnf.d/mariadb-server.cnf
      regexp: '^#bind-address= 0.0.0.0'
      line: bind-address= 0.0.0.0

  - name: Restart MariaDB
    ansible.builtin.service:
      name: mariadb
      state: restarted
    
  - name: MariaDB started on boot
    ansible.builtin.shell: sudo systemctl enable mariadb
  
  - name: Create user daan
    ansible.builtin.shell: mysql -u root -e "CREATE USER 'daan'@localhost IDENTIFIED BY 'daan0409';"
  
  - name: Give user daan all rights
    ansible.builtin.shell: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'daan'@localhost IDENTIFIED BY 'daan0409'"
