- name: Install phpmyadmin
  hosts: web
  remote_user: root

  - name: Download phpmyadmin
    get_url:
      url: https://files.phpmyadmin.net/phpMyAdmin/5.1.1/phpMyAdmin-5.1.1-all-languages.zip
      dest: /root/phpmyadmin.zip
  
  - name: Extract phpmyadmin
    ansible.builtin.unarchive:
      remote_src: yes
      src: /root/phpmyadmin.zip
      dest: /var/www/html/phpmyadmin
  
  - name: Copy phpmyadmin config
    ansible.builtin.copy:
      src: /var/www/html/phpmyadmin/config.sample.inc.php
      dest: /var/www/html/phpmyadmin/config.inc.php
      mode: '0644'
  
  - name: Configure to user the external SQL database
    ansible.builtin.lineinfile:
      path: /var/www/html/phphmyadmin/config.inc.php
      regexp: '^$cfg['Servers'][$i]['host'] = 'localhost';'
      line: $cfg['Servers'][$i]['host'] = '192.168.123.13';