- name: Install Wordpress
  hosts: web
  remote_user: root

tasks:
- name: Download Wordpress
  get_url:
    url: https://nl.wordpress.org/latest-nl_NL.zip
    dest: /root/wordpress.zip

- name: Extract Wordpress
  ansible.builtin.unarchive:
    remote_src: yes
    src: /root/wordpress.zip
    dest: /var/www/html/

  - name: Rename wordpress folder
    ansible.builtin.shell: mv /var/www/html/wordpress /var/www/html/DOMAIN

  - name: Copy Wordpress config
    ansible.builtin.copy:
      remote_src: yes
      src: /var/www/html/phpmyadmin/wp-config-sample.php
      dest: /var/www/html/phpmyadmin/wp-config.php
      mode: '0644
