- name: Install filebeat
  hosts: jenkins
  tasks:
  - name: Download Filebeat RPM
    get_url:
      url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.14.1-x86_64.rpm
      dest: /home/localadmin/filebeat.rpm

  - name: Install Filebeat
    ansible.builtin.shell: echo 'daan0409' | sudo -S rpm -i filebeat.rpm

  - name: Install Filebeat config
    ansible.builtin.shell: echo 'daan0409' | sudo -S wget -r ftp://localadmin:daan0409@192.168.123.12/filebeat.yml -O /etc/filebeat/filebeat.yml

  - name: Filebeat setup
    ansible.builtin.shell: echo 'daan0409' | sudo -S filebeat modules enable system

  - name: Enable Filebeat service
    ansible.builtin.shell: echo 'daan0409' | sudo -S systemctl enable filebeat

  - name: Start Filebeat service
    ansible.builtin.shell: echo 'daan0409' | sudo -S systemctl start filebeat
