- name: Install Metricbeat
  hosts: debian
  tasks:
  - name: Download Metricbeat DEB
    get_url:
      url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.14.1-amd64.deb
      dest: /home/localadmin/metricbeat.deb

  - name: Install Metricbeat
    ansible.builtin.shell: echo 'daan0409' | sudo -S rpm -i metricbeat.deb

  - name: Install Metricbeat config
    ansible.builtin.shell: echo 'daan0409' | sudo -S wget -r ftp://localadmin:daan0409@192.168.123.12/metricbeat.yml -O /etc/metricbeat/metricbeat.yml

  - name: Setup Metricbeat
    ansible.builtin.shell: echo 'daan0409' | sudo -S metricbeat setup -e

  - name: Enable Metricbeat service
    ansible.builtin.shell: echo 'daan0409' | sudo -S systemctl enable metricbeat

  - name: Start Metricbeat service
    ansible.builtin.shell: echo 'daan0409' | sudo -S systemctl start metricbeat
