- name: Install Lynis
  hosts: redhat
  tasks:
  - name: Updating packages
    ansible.builtin.shell: sudo yum update -y ca-certificates curl nss openssl

  - name: Install Lynis repo
    ansible.builtin.shell: sudo curl https://raw.githubusercontent.com/rouwens/Fontys/S4/Ansible/lynis.repo -o /etc/yum.repos.d/lynis.repo

  - name: Install Lynis
    ansible.builtin.shell: sudo yum install -y lynis
    